### ISSUE TITLE
Signal Projects dashboard modal displays "NaN" under "Updated" field

### ISSUE THREAD

**Issue by tcwcodes** [cityofaustin/atd-data-and-performance#327]
@tcwcodes commented on [Thu Oct 10 2019](https://github.com/cityofaustin/atd-vz-data/issues/275)

https://transportation.austintexas.io/signal-projects/

---

@mateoclarke commented on [Sun Oct 13 2019](https://github.com/cityofaustin/atd-vz-data/issues/275#issuecomment-541503195)

@tcwcodes I think you added this issue to the wrong repo. Can you move it to https://github.com/cityofaustin/transportation.austintexas.io

---

@tcwcodes commented on [Mon Oct 14 2019](https://github.com/cityofaustin/atd-vz-data/issues/275#issuecomment-541736519)

> @tcwcodes I think you added this issue to the wrong repo. Can you move it to https://github.com/cityofaustin/transportation.austintexas.io

You're right, I must have left it under the default branch by accident. Moving it now, thanks for the heads up!

**Comment by TracyLinder** [comment]
@tcwcodes Can you move this card to the correct pipeline please?

**Comment by tcwcodes** [comment]
> @tcwcodes Can you move this card to the correct pipeline please?

Done, thanks @TracyLinder!

**Comment by amenity** [comment]
@tcwcodes - was this something you worked on or have in progress? Will you assign an estimate and make sure the milestone is accurate?

**Comment by amenity** [comment]
Also, is this a duplicate of #323?

**Comment by tcwcodes** [comment]
Closing this since it no longer appears to be an issue

**Comment by amenity** [comment]
@tcwcodes - I'm still seeing this:
<img width="1397" alt="Screen Shot 2020-01-06 at 1 03 02 AM" src="https://user-images.githubusercontent.com/1463708/71836253-4b41c900-3079-11ea-955d-a48e483399ce.png">

**Comment by tcwcodes** [comment]
@amenity, thanks for bringing this to my attention! I moved this back on deck and will work on zapping this bug!

**Comment by amenity** [comment]
@tcwcodes - Looks like we missed this in planning, sorry! Any update on this issue? ⚡🐛

**Comment by tcwcodes** [comment]
Thanks, @amenity! I moved it to in progress - I think the previous estimate still applies. I'm going to work on this one now.
